user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

sms:
    resource: "@SMSBundle/Controller/"
    type:     annotation
    prefix:   /



event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

enfants:
    resource: "@EnfantsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

facture:
    resource: "@FactureBundle/Resources/config/routing.yml"
    prefix:   /

mobileapi:
    resource: "@MobileapiBundle/Resources/config/routing.yml"
    prefix:   /api

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation










club_membre:
    resource: "@ClubBundle/Controller/MembreController.php"
    type:     annotation

club_equipement:
    resource: "@ClubBundle/Controller/EquipementController.php"
    type:     annotation

club_club:
    resource: "@ClubBundle/Controller/ClubController.php"
    type:     annotation



delete:
    path:     /delete{idclub}
    defaults: { _controller: ClubBundle:club:delete }

del1:
    path:     /del1/{id}
    defaults: { _controller: ClubBundle:Membre:del1 }

new2:
    path:     /new2/{idclub}
    defaults:  {_controller: ClubBundle:Membre:new2 }

indexfront:
    path:     /indexfront
    defaults:  {_controller: ClubBundle:Membre:indexfront }

mail:
    path:     /mail/{id}
    defaults: { _controller: ClubBundle:Membre:mail }